### PR TITLE
This allows us to set up the storing mode via conf file

### PR DESCRIPTION
**Pull request by ramonfontes**
I have validated with Mininet-WiFi. The code below automates all the process:

https://github.com/intrig-unicamp/mininet-wifi/blob/master/examples/6LoWPan.py

### CODE REVIEW

**Comment by Stefan-Schmidt** [comment]
@alexaring rpld is your baby, could you have a look at this PR?

**Comment by alexaring** [comment]
@ramonfontes can you please specify the use case here because we don't support more than those bits set.

**Comment by ramonfontes** [comment]
Dear @alexaring,

This is only an initial support. As you can see below, we can observe the mode of operation with this PR. This is especially important for teaching.

storing-mode

non-storing-mode

**Comment by alexaring** [comment]
In your example you switching to non-storing mode which we already support. Still I have no idea what you are trying to do there...

https://github.com/linux-wpan/rpld/tree/nonstoring_mode

We should merge that branch to master.

**Comment by ramonfontes** [comment]
> We should merge that branch to master.

Well, I didn't notice that branch. Yes, I think you should do that.

**Comment by alexaring** [comment]
https://legacy.netdevconf.info/0x14/session.html?talk-extend-segment-routing-for-RPL

@ramonfontes for your teaching stuff

**Comment by ramonfontes** [comment]
Thanks for sharing those artifacts @alexaring. I made a [demo - in Portuguese](https://www.youtube.com/watch?v=-UyE9urUgjQ) public as well.

The paper is really interesting and I'll consider it in my class. Thanks again for sharing it and thank you for rpld.

**Pull request closed without merging**
